### PR TITLE
Updated instructions

### PR DESCRIPTION
**Pull request by stgogm**
Improved usage instructions in README.md

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Is this still up-to-date? This seems like an enormous amount of changes.

**Comment by stgogm** [comment]
No, I'm sorry. I ended up creating a separate version of this module https://github.com/FinalDevStudio/ng-scroll-glue

**Comment by oliversalzburg** [comment]
Oh, I see. What did you add in your fork? Any interest in re-integrating? :)

**Comment by stgogm** [comment]
Mainly changed the name to something more descriptive. Now I'm working on the couple of issues that are active.

Feel free to add any issues at https://github.com/FinalDevStudio/ng-scroll-glue :)

**Pull request closed without merging**
