### PR TITLE
fix(apply): ensure scroll even if scope.$apply() is call

### PR DESCRIPTION
**Pull request by liollury**
This fix works with karma tests

### CODE REVIEW

**Review by oliversalzburg — CHANGES_REQUESTED** [review]

**Comment by liollury** [comment]
Yes it useless. i have change it but the pull request got all modification. So if you want this : there is a new attribute "force-glue" that scroll even if user isn't at the end. And 'scroll-glue-anchor' that is a child to watch for size.
Noob in pull request sry :)

**Review by oliversalzburg — APPROVED** [review]

**Comment by oliversalzburg** [comment]
I don't really see the need for `force-glue`. Shouldn't that be identical to supplying a truthy argument for `scroll-glue`?

The tests fail because the scrolling is now happening one frame later, due to the use of $timeout. As this is timing related, the outcome of the tests can be different between Travis and your machine.

I'm pretty sure we'll get it to work though :)

A few hints regarding PRs. You're going to want to [*squash* your commits](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/). Meaning that you generate a single commit that contains all the changes you've made so far. This is often much easier when you haven't opened the PR from your master branch. Thus, it is helpful to create a separate branch for each PR you're going to open against an upstream repository. Because you've opened this PR from your master branch, you're going to want to do an interactive rebase as described in the linke article.

When you have made changes to your PR, you're usually going to want to commit them with `git commit --amend` to just change that latest commit and still end up with a single commit in your PR. You'll need to push that branch with `git push -f`, which is another reason why it's useful to open PRs from a feature branch.

Hope I could help :)

**Comment by liollury** [comment]
Force-glue cancel isAttach check, so if user scroll to top (for scroll-glue-bottom example) and Force-glue is on, any change will scroll. In my tests, without this attribute, if user scroll top, scroll glue is deactivated until user scroll down again. Il dont know if it is clear (sry, french english power) :-)

**Comment by liollury** [comment]
Oh and thanks for your pull request explaination !

**Comment by oliversalzburg** [comment]
Okay I understand now. For the future, it's usually easier to keep every PR to a single feature/fix, that makes it easier to argue about the change and merge it (another reason to have individual feature branches) ;)

Regarding the tests, you're probably going to want to change the checks so that they only run after a `$timeout` as well, or you could mock `$timeout` and just have it invoke the target function instantly instead of on the next frame. That should fix the tests.

**Comment by liollury** [comment]
Ok i'll know now how to do a clean PR :)
i've mock ```$timeout``` in tests and it works properly.

**Comment by oliversalzburg** [comment]
Excellent work! Would you mind maybe adding a short usage example of the new attributes to https://github.com/Luegg/angularjs-scroll-glue#usage

**Comment by liollury** [comment]
It's ok !

**Comment by oliversalzburg** [comment]
I cleaned up the commits. Please have a look at https://github.com/Luegg/angularjs-scroll-glue/pull/56 and check if you think it's ready for merge.

**Comment by liollury** [comment]
It's ok for me.

Le lun. 30 janv. 2017 à 12:20, Oliver Salzburg <notifications@github.com> a
écrit :

**Comment by oliversalzburg** [comment]
Closed in favor of #56

**Pull request closed without merging**
