### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stgogm**
Added a more explicit example to ease the usage of this directive.

### CODE REVIEW

**Comment by chrismbarr** [comment]
+1 for these changes, seeing `luegg.directives` in our application is a little confusing for those who are new to this module.  A more normal/descriptive name would be appreciated!

**Comment by Luegg** [comment]
Hm, renaming the module would break all client code, I'm not sure if this is wort it.

@stgogm can you re-pull just the changes to the readme for now?

**Comment by stgogm** [comment]
@Luegg I've sent the pull request for the README.md update.

@chrismbarr I'll create a fork with a more descriptive name leaving the functionality intact.

**Comment by stgogm** [comment]
@chrismbarr Here it is https://github.com/stgogm/ng-scroll-glue

**Pull request closed without merging**
