### PR TITLE
Added ability to specify that scrollglue work with horizontal scrolling ...

### PR DESCRIPTION
**Pull request by dotfrank**
...divs.  So you can have something like a horizontal scrolling div, which has data populated and as it overflows towards the right, the div automatically scrolls to keep up with new data.  No tests have been added for this.

### CODE REVIEW

**Comment by Luegg** [comment]
Unfortunately, using an isolated scope breaks compatibility with other directives requiring a scope (see #10). That's why the two tests fail.

**Comment by Luegg** [comment]
I'm also thinking about changing the API. It would probably make more sense to activate horizontal scrolling by default but adding two further directives scrollGlueHorizontal and scrollGlueVertical.

So users can continue using the scrollGlue directive which scrolls in both directions but can fall back to scrollGlueHorizontal/scrollGlueVertical if they explicitly want to specify the direction. This would also allow to bind whether a scroll direction should be enabled or not.

**Comment by dotfrank** [comment]
Hi Luegg,

Ah, I was not aware of the issues the isolated scope would create.  

So to verify I understand correctly, both horiz/vert scrolling would be enabled by default with the current directive, correct?  Then we would have separate directives that either perform h/v scrolling?  

That works for the specific cases you and I want - I wonder whether left-scrolling or up-scrolling could easily be supported?  

In that case 5 total directives would be kind of messy no?  Instead why don't we pass in the "direction" like I had it, except instead of using an isolated scope, how about we just use the elements attributes?

Like in the current link function: 
`activationState = createActivationState(attrs.scrollGlue, scope);`
and html directive: 
`<div scroll-glue="glued">`
could we have a direction attribute in addition to scroll-glue?

**Comment by Luegg** [comment]
Additional attributes should be easy. But I kind of like the idea of having 5 directives (one for each direction and the default with glue to bottom-right). This would make using the directive in a more complex setting dead easy.

Imagine, you want to use two separate buttons to control the glue horizontally and vertically. Having a `scroll-glue-bottom` and a `scroll-glue-right` directive would require something like:

```
<button ng-click="glueX=!glueX">Toggle X</button>
<button ng-click="glueY=!glueY">Toggle Y</button>

<div scroll-glue-bottom="glueX" scroll-glue-right="glueY">
...
</div>
```

The protocol is simply as "set this to true and it is glued"...

Having a direction attribute would require a bit more sophisticated protocol. We would have to parse the direction attribute and encode all possible directions like `bottom`, `bottom-right`, `right-top` etc.

**Comment by ashclarke** [comment]
@Luegg Hi, is there any plan to include this change in a new release soon? Thanks!

**Comment by Luegg** [comment]
Done :)

**Comment by ashclarke** [comment]
Great! Thanks Luegg!

**Pull request closed without merging**
